import { describe, expect, test } from 'vitest';
import { mkdtempSync, readFileSync, writeFileSync } from 'fs';
import os from 'os'; import path from 'path';
import { createApprovalStore, ApprovalStoreError } from '../lib/approval-store.js';
const binding={agent:'worker',project:'p',project_room_id:'!p:test',owner_mxid:'@owner:test',owner_dm_room_id:'!dm:test'};
function setup(options={}) { const dir=mkdtempSync(path.join(os.tmpdir(),'approval-proj-')); const file=path.join(dir,'store.json'); const store=createApprovalStore(file,{now:()=>1000,...options}); store.upsertBinding(binding); return {store,file}; }
function create(store,id='up-1'){return store.createRequest({agent:'worker',runtime:'codex',project:'p',project_room_id:'!p:test',upstream_request_id:id,tool_name:'Bash',input_preview:'pwd'},{routerApprovalId:id});}
describe('approval projection store',()=>{
 test('creation and transitions enqueue increasing canonical revisions',()=>{const {store}=setup();const r=create(store);expect(r).not.toHaveProperty('projection_revision');expect(store.getRequest(r.id,{matrix:true})).not.toHaveProperty('projection_revision');let q=store.listDueProjections();expect(q.map(x=>x.channel)).toEqual(['private_request','public_notice']);const m=store.getRequest(r.id,{matrix:true});store.submitMatrixVerdict(r.id,{action:'approve_once',sender_mxid:m.owner_mxid,room_id:m.owner_dm_room_id,agent:m.agent,project:m.project,project_room_id:m.project_room_id,input_digest:m.input_digest});expect(store.listDueProjections().at(-1)).toMatchObject({revision:2,channel:'private_status',state:'approved'});store.consumeDecision(r.id,'worker',m.input_digest);expect(store.listDueProjections().at(-1)).toMatchObject({revision:3,state:'consumed'});});
 test('prepare is first-writer-wins and begin receipt use exact CAS',()=>{const {store}=setup();create(store);const row=store.listDueProjections()[0];const a=store.prepareProjection(row.cas_token,{publisher_mxid:'@bot:test',homeserver:'test',credential_kind:'local_bot',credential_generation:'g1',payload_version:1,prepared_event_type:'m.room.message',prepared_payload:{body:'x'}});const b=store.prepareProjection(row.cas_token,{publisher_mxid:'@other:test',homeserver:'test',credential_kind:'local_bot',credential_generation:'g2',payload_version:1,prepared_event_type:'m.room.message',prepared_payload:{body:'y'}});expect(b.plan).toEqual(a.plan);expect(store.beginProjectionSend(a.plan.cas_token).plan.attempt_state).toBe('attempted');expect(()=>store.receiptProjection(a.plan.cas_token,{event_id:'$e',publisher_mxid:'@other:test'})).toThrow(ApprovalStoreError);expect(store.receiptProjection(a.plan.cas_token,{event_id:'$e',publisher_mxid:'@bot:test'}).event_id).toBe('$e');});
 test('prepared payload is bounded and retry preserves immutable identity',()=>{const {store}=setup();create(store);const row=store.listDueProjections()[0];expect(()=>store.prepareProjection(row.cas_token,{publisher_mxid:'@bot:test',homeserver:'test',credential_kind:'local_bot',credential_generation:'g',prepared_event_type:'m.room.message',prepared_payload:{body:'x'.repeat(70000)}})).toThrowError(/too large/);const ready=store.prepareProjection(row.cas_token,{publisher_mxid:'@bot:test',homeserver:'test',credential_kind:'local_bot',credential_generation:'g',prepared_event_type:'m.room.message',prepared_payload:{body:'x'}}).plan;store.beginProjectionSend(ready.cas_token);expect(store.retryProjection(ready.cas_token,{retry_at:2000,error_code:'timeout'})).toEqual({attempt_state:'uncertain'});expect(store.listDueProjections()[0].plan).toMatchObject({publisher_mxid:'@bot:test',credential_generation:'g',prepared_payload:{body:'x'},attempt_state:'uncertain'});});
 test('pre-rename failure rolls memory back while post-rename failure stays committed',()=>{let phase='';const fsFault=(name)=>{if(phase===name)throw new Error(name)};const {store,file}=setup({fsFault});phase='beforeRename';expect(()=>create(store)).toThrow();expect(store.listRequests()).toHaveLength(0);expect(JSON.parse(readFileSync(file)).requests).toEqual({});phase='afterRename';expect(()=>create(store,'up-2')).not.toThrow();expect(store.listRequests()).toHaveLength(1);expect(store.persistenceHealth().degraded).toBe(true);expect(Object.keys(JSON.parse(readFileSync(file)).requests)).toHaveLength(1);});
 test('binding removal and swept expiry use the same revision path',()=>{let now=1000;const {store}=setup({now:()=>now,ttlMs:10});const a=create(store,'bind');store.removeBinding('worker','!p:test');expect(store.listDueProjections().at(-1)).toMatchObject({request_id:a.id,revision:2,state:'denied'});store.upsertBinding(binding);const b=create(store,'expire');now=2000;expect(store.sweepExpired({limit:1})).toEqual({scanned:1,expired:1});expect(store.listDueProjections().at(-1)).toMatchObject({request_id:b.id,revision:2,state:'expired'});});
 test('v1 migration is bounded and emits no actionable work',()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'approval-v1-'));const file=path.join(dir,'store.json');const req={id:'old',agent:'worker',runtime:'codex',project:'p',projectRoomId:'!p:test',ownerMxid:'@owner:test',ownerDmRoomId:'!dm:test',upstreamRequestId:'u',inputDigest:'d',status:'pending',decision:null,createdAt:1,expiresAt:999999};writeFileSync(file,JSON.stringify({version:1,bindings:{},requests:{old:req},audit:[]}));const store=createApprovalStore(file,{now:()=>1000,migrationBatchSize:1});expect(store.listDueProjections()).toEqual([expect.objectContaining({channel:'private_status',state:'pending',migration_kind:'legacy_v1'})]);expect(store.listDueProjections().some(x=>x.channel==='private_request'||x.channel==='public_notice')).toBe(false);});
});
